/**
 * Indian Market Signal Engine - Frontend Application
 * 
 * This script loads the latest.json report generated by the Python analysis engine
 * and displays it in an interactive format.
 * 
 * Frontend-only presentation for the Phase 8 production artifact.
 */

document.addEventListener('DOMContentLoaded', function() {
    loadAnalysis();
});

/**
 * Load and display the latest analysis report
 */
async function loadAnalysis() {
    try {
        const response = await fetch('data/latest.json');
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        displayAnalysis(data);
        
    } catch (error) {
        console.error('Error loading analysis:', error);
        showError();
    }
}

/**
 * Display the analysis results
 */
function displayAnalysis(data) {
    // Hide loading, show content
    document.getElementById('loading').style.display = 'none';
    document.getElementById('content').style.display = 'block';

    displayHeader(data);
    displayTop10(data.selected_stocks || [...(data.large_cap || []), ...(data.mid_cap || [])]);

    // Display large cap stocks
    const rankMap = new Map();
    (data.selected_stocks || []).forEach((stock, index) => rankMap.set(String(stock.symbol || '').trim(), index + 1));
    displaySegment(data.large_cap || [], 'large-cap-list', rankMap);

    // Display mid cap stocks
    displaySegment(data.mid_cap || [], 'mid-cap-list', rankMap);

    // Display warnings if any
    if (data.warnings && data.warnings.length > 0) {
        displayWarnings(data.warnings);
    }
}

function displayHeader(data) {
    const timestamp = document.getElementById('data-timestamp');
    const date = data.analysis_timestamp || data.generated_at || data.data_as_of;
    timestamp.textContent = date ? `Updated: ${formatDate(date, false)}` : 'Update date unavailable';
    const coverage = document.getElementById('coverage-summary');
    coverage.textContent = `${displayValue(data.eligible_count)} of ${displayValue(data.universe_count)} eligible`;
}

function displayTop10(stocks) {
    const container = document.getElementById('top-10-summary');
    container.innerHTML = '';
    stocks.slice(0, 10).forEach((stock, index) => {
        const label = getScoreLabel(stock.score);
        const row = document.createElement('button');
        row.type = 'button';
        row.className = 'summary-row';
        row.setAttribute('aria-label', `View ${stock.symbol}`);
        row.innerHTML = `<span class="summary-rank">${index + 1}</span><span><span class="summary-symbol">${escapeHtml(stock.symbol)}</span><span class="stock-separator" aria-hidden="true"> · </span><span class="summary-name">${escapeHtml(stock.name || 'Name unavailable')}</span></span><span class="summary-score">${formatNumber(stock.score, 1)}</span><span class="summary-label">${label.icon} ${label.text.replace(' Signal', '')}</span>`;
        row.addEventListener('click', () => document.getElementById(`stock-${cssId(stock.symbol)}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }));
        container.appendChild(row);
    });
}

/**
 * Display stocks for a segment
 */
function displaySegment(stocks, containerId, rankMap) {
    const container = document.getElementById(containerId);
    container.innerHTML = '';

    if (!stocks || stocks.length === 0) {
        container.innerHTML = '<p>No recommendations at this time</p>';
        return;
    }

    stocks.forEach((stock, index) => {
        const card = createStockCard(stock, rankMap.get(String(stock.symbol || '').trim()) || index + 1);
        container.appendChild(card);
    });
}

/**
 * Create a stock card element
 */
function createStockCard(stock, index) {
    const card = document.createElement('div');
    card.className = 'stock-card';
    card.id = `stock-${cssId(stock.symbol)}`;

    const label = getScoreLabel(stock.score);
    const metrics = stock.metrics || {};
    const indicators = stock.indicators || {};
    const strengths = stock.explanations?.strengths || [];
    const cautions = getCautions(stock);
    const notes = getSelectionNotes(stock.selection_reason || []);
    const score = Number.isFinite(Number(stock.score)) ? Number(stock.score) : null;

    card.innerHTML = `
        <div class="stock-card-header">
            <div>
                <div class="rank-mark">#${index}</div>
                <div class="stock-symbol">${escapeHtml(stock.symbol)} <span class="stock-separator" aria-hidden="true">·</span> <span class="stock-name">${escapeHtml(stock.name || 'Name unavailable')}</span></div>
                <div class="sector">${escapeHtml(stock.sector || 'Sector unavailable')} <span class="segment-pill">${escapeHtml(stock.segment || '')}</span></div>
            </div>
            <span class="signal-badge ${label.className}">${label.icon} ${label.text}</span>
        </div>

        <div class="stock-score">${score === null ? 'Not available' : `${score.toFixed(1)}/100`}</div>
        <div class="score-context">Quantitative score out of 100. Higher scores indicate stronger current technical characteristics according to this model. It is not a probability of future returns.</div>

        <div class="score-bar">
            <div class="score-fill" style="width: ${score === null ? 0 : Math.max(0, Math.min(100, score))}%"></div>
        </div>

        <div class="performance-title">Recent Performance</div>
        <div class="performance-grid">
            ${['return_1m', 'return_3m', 'return_6m'].map((key, i) => `<div class="performance-item"><span>${['1M', '3M', '6M'][i]}</span><strong>${formatPercent(metrics[key])}</strong></div>`).join('')}
        </div>
        <div class="price-line"><span>Current Price</span><strong>${formatPrice(metrics.price)}</strong></div>
        <div class="rsi-line"><strong>RSI (14): ${formatNumber(metrics.rsi, 1)}</strong> &middot; ${getRsiInterpretation(metrics.rsi)}</div>

        <div class="why-section"><div class="why-title">Why selected</div><ul class="why-list">${strengths.length ? strengths.map(item => `<li>${escapeHtml(item)}</li>`).join('') : '<li>Qualifying model characteristics</li>'}</ul></div>
        ${cautions.length ? `<div class="caution-section"><div class="caution-title">Caution</div><ul class="caution-list">${cautions.map(item => `<li>${escapeHtml(item)}</li>`).join('')}</ul></div>` : ''}
        ${notes.length ? `<ul class="selection-notes">${notes.map(item => `<li>${escapeHtml(item)}</li>`).join('')}</ul>` : ''}
        <details class="details"><summary>View score details</summary><div class="breakdown">${renderBreakdown(stock.factor_scores || {})}</div></details>
    `;

    return card;
}

/**
 * Display warnings
 */
function displayWarnings(warnings) {
    const warningsSection = document.getElementById('warnings-section');
    const warningsList = document.getElementById('warnings-list');

    warningsList.innerHTML = '';
    warnings.forEach(warning => {
        const li = document.createElement('li');
        li.textContent = warning;
        warningsList.appendChild(li);
    });

    warningsSection.style.display = 'block';
}

/**
 * Show error state
 */
function showError() {
    document.getElementById('loading').style.display = 'none';
    document.getElementById('content').style.display = 'none';
    document.getElementById('error').style.display = 'block';
}

/**
 * Get CSS class for signal
 */
function getSignalClass(signal) {
    const signalLower = (signal || 'WEAK').toLowerCase();
    if (signalLower === 'strong') return 'strong';
    if (signalLower === 'positive') return 'positive';
    if (signalLower === 'watch') return 'watch';
    return 'weak';
}

function getScoreLabel(score) {
    if (!Number.isFinite(Number(score))) return { text: 'Signal unavailable', icon: '', className: 'watch' };
    const value = Number(score);
    if (value >= 90) return { text: 'Exceptional Signal', icon: '⭐', className: 'exceptional' };
    if (value >= 80) return { text: 'Strong Signal', icon: '🟢', className: 'strong' };
    if (value >= 70) return { text: 'Positive Signal', icon: '🟢', className: 'positive' };
    return { text: 'Watch', icon: '🟡', className: 'watch' };
}

function getRsiInterpretation(value) {
    if (!Number.isFinite(Number(value))) return 'Not available';
    const rsi = Number(value);
    if (rsi < 30) return 'Oversold';
    if (rsi < 50) return 'Weak / below average momentum';
    if (rsi < 70) return 'Healthy momentum';
    if (rsi <= 80) return 'Strong momentum, but relatively extended';
    return 'Very strong momentum, but highly extended';
}

function getCautions(stock) {
    const metrics = stock.metrics || {};
    const indicators = stock.indicators || {};
    const cautions = [];
    if (Number.isFinite(Number(metrics.rsi)) && Number(metrics.rsi) >= 70) cautions.push(`RSI ${Number(metrics.rsi).toFixed(1)} — strong momentum but relatively extended.`);
    if (Number.isFinite(Number(indicators.distance_from_52w_high)) && Number(indicators.distance_from_52w_high) >= -0.03) cautions.push('Trading near its 52-week high.');
    if (Number.isFinite(Number(indicators.max_drawdown)) && Number(indicators.max_drawdown) <= -0.20) cautions.push('Historical drawdown indicates meaningful downside volatility.');
    return cautions;
}

function getSelectionNotes(reasons) {
    return reasons.filter(reason => !/^Score /.test(reason)).map(reason => reason === 'Top-ranked within segment' ? 'Top-ranked within its segment.' : reason === 'Sector limit satisfied' ? 'Sector diversification rule satisfied.' : reason === 'Selected after minimum score filter' ? 'Met the minimum score threshold.' : reason);
}

function renderBreakdown(factors) {
    const labels = { momentum: ['Momentum', 20], trend: ['Trend', 20], relative_strength: ['Relative Strength', 15], volume: ['Volume', 10], rsi: ['RSI', 10], '52_week_strength': ['52-Week Strength', 10], risk: ['Risk Profile', 15] };
    return Object.entries(labels).map(([key, [label, maximum]]) => `<span>${label}</span><span>${formatNumber(factors[key], 1)} / ${maximum}</span>`).join('');
}

/**
 * Format date string
 */
function formatDate(dateStr, includeTime = true) {
    try {
        const date = new Date(dateStr);
        return date.toLocaleDateString('en-IN', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            ...(includeTime ? { hour: '2-digit', minute: '2-digit' } : {}),
            timeZone: 'Asia/Kolkata'
        });
    } catch {
        return dateStr;
    }
}

/**
 * Format percentage
 */
function formatPercent(value) {
    if (!Number.isFinite(Number(value))) return 'Not available';
    const percentage = Number(value) * 100;
    const sign = percentage >= 0 ? '+' : '';
    return `${sign}${percentage.toFixed(2)}%`;
}

function formatPrice(value) {
    if (!Number.isFinite(Number(value))) return 'Not available';
    return `₹${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatNumber(value, digits = 1) {
    return Number.isFinite(Number(value)) ? Number(value).toFixed(digits) : 'Not available';
}

function displayValue(value) {
    return Number.isFinite(Number(value)) ? Number(value).toLocaleString('en-IN') : 'Not available';
}

function cssId(value) {
    return String(value || '').replace(/[^a-zA-Z0-9_-]/g, '-');
}

function escapeHtml(value) {
    return String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
}

// Example: Refresh every hour if running in a browser
setInterval(function() {
    // Optional: refresh data periodically
    // loadAnalysis();
}, 3600000);
